### ISSUE TITLE
MetaMaskSDK is not a constructor

### ISSUE THREAD

**Issue by Park6102** [MetaMask/metamask-sdk#120]
Is there any solution?

■Code
import MetaMaskSDK from '@metamask/sdk';
const options = {
  injectProvider: false,
  communicationLayerPreference: 'webrtc',
};

const MMSDK = new MetaMaskSDK(options);

■Error
MetaMaskSDK is not a constructor

**Comment by abretonc7s** [comment]
Could you try `import {MetaMaskSDK} from '@metamask/sdk';` ?

**Comment by Park6102** [comment]
> Could you try `import {MetaMaskSDK} from '@metamask/sdk';` ?
The above problem was solved but another error occurred

ReferenceError: RTCPeerConnection is not defined
    at new io (C:\meta\node_modules\@metamask\sdk\dist\node\cjs\metamask-sdk.js:21:96845)
    at ro.initCommunicationLayer (C:\meta\node_modules\@metamask\sdk\dist\node\cjs\metamask-sdk.js:21:103475)
    at new ro (C:\meta\node_modules\@metamask\sdk\dist\node\cjs\metamask-sdk.js:21:103069)
    at Rh.initializeConnector (C:\meta\node_modules\@metamask\sdk\dist\node\cjs\metamask-sdk.js:41:115156)
    at new Rh (C:\meta\node_modules\@metamask\sdk\dist\node\cjs\metamask-sdk.js:41:114752)
    at Lh.initialize (C:\meta\node_modules\@metamask\sdk\dist\node\cjs\metamask-sdk.js:41:128027)
    at new Lh (C:\meta\node_modules\@metamask\sdk\dist\node\cjs\metamask-sdk.js:41:126768)
    at file:///C:/meta/a.js:8:15
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.0
