### ISSUE TITLE
[Bug]: Android com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by awbernardin0** [MetaMask/metamask-sdk#629]
### SDK

React-Native

### Provide environment information

<img width="762" alt="Screenshot 2024-01-23 at 1 27 06 PM" src="https://github.com/MetaMask/metamask-sdk/assets/153701190/96a81e32-23c7-4f3c-a0b1-6481e5746668">
<img width="689" alt="Screenshot 2024-01-23 at 1 29 53 PM" src="https://github.com/MetaMask/metamask-sdk/assets/153701190/ad511d28-ad3e-4d31-923a-15d708bf62d8">

### MetaMask SDK Version

"@metamask/sdk-react": "^0.14.2"

### MetaMask Mobile app Version

MetaMask v7.12.3(1230)

### Describe the Bug

After adding SDKConfigProvider and MetaMaskProvider to my App.tsx file I'm having this error on Android only, iOS is working fine.

<img width="596" alt="Screenshot 2024-01-23 at 1 10 37 PM" src="https://github.com/MetaMask/metamask-sdk/assets/153701190/f8504765-5eaf-4995-a120-eae8e472e5e0">

--------- beginning of system
--------- beginning of crash
2024-01-22 19:16:56.415   575-625   VerityUtils             system_server                        E  Failed to measure fs-verity, errno 1: /data/app/~~cX9hGbuCXCfkVMMKLMZM7w==/io.metmos.app-23DWzp3HgaIlyBaQnFEq9g==/base.apk
2024-01-22 19:18:11.226 14092-14355 AndroidRuntime          pid-14092                            E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: io.metmos.app, PID: 14092
                                                                                                    java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
                                                                                                    	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:102)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:356)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-01-22 19:24:11.201   575-758   UserRestrictionsUtils   system_server                        E  Unknown restriction queried by uid 1000 (com.android.location.fused et al): io.metmos.app
2024-01-22 19:24:12.692   575-2399  AppOps                  system_server                        E  package io.metmos.app not found, can't check for attributionTag null
2024-01-22 19:24:12.692   575-2399  AppOps                  system_server                        E  Bad call made by uid 1000. Package "io.metmos.app" does not belong to uid 10170.
2024-01-22 19:24:12.704   575-2399  AppOps                  system_server                        E  noteOperation
                                                                                                    java.lang.SecurityException: Specified package "io.metmos.app" under uid 10170 but it is not
                                                                                                    	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4694)
                                                                                                    	at com.android.server.appop.AppOpsService.noteOperationUnchecked(AppOpsService.java:3453)
                                                                                                    	at com.android.server.appop.AppOpsService.noteOperationImpl(AppOpsService.java:3441)
                                                                                                    	at com.android.server.appop.AppOpsService.-$$Nest$mnoteOperationImpl(Unknown Source:0)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.lambda$noteOperation$4(AppOpsService.java:7640)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.$r8$lambda$oOwUoG55BBmJ6yiwhp3OAq3tQ30(Unknown Source:0)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher$$ExternalSyntheticLambda1.apply(Unknown Source:32)
                                                                                                    	at com.android.server.policy.AppOpsPolicy.noteOperation(AppOpsPolicy.java:227)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.noteOperation(AppOpsService.java:7638)
                                                                                                    	at com.android.server.appop.AppOpsService.noteOperation(AppOpsService.java:3425)
                                                                                                    	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:479)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1280)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1244)
2024-01-22 20:06:49.616   575-625   VerityUtils             system_server                        E  Failed to measure fs-verity, errno 1: /data/app/~~VEHAJdTnVO1AWgSP02WYMQ==/io.metmos.app-2iPJ5_P7P7O2uvAjDBykNg==/base.apk
2024-01-22 20:07:06.975 18345-18426 AndroidRuntime          pid-18345                            E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: io.metmos.app, PID: 18345
                                                                                                    java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
                                                                                                    	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:102)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:356)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)

### Expected Behavior

Expected to show the Login screen like on iOS.

### To Reproduce

Wrap the App.tsx content to SDKConfigProvider and MetaMaskProvider and re-run the app

**Comment by andreahaku** [comment]
Hi @awbernardin0 we are looking into it.

Can you please test the [RN Demo](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo) and see if you have the same issue?

Also can you please try by removing the `SDKConfigProvider ` and only use `MetaMaskProvider`.

Thanks.

**Comment by awbernardin0** [comment]
HI @andreahaku, 

I already tested the RN Demo together with amplify v5 (React Native) and I have the same issue.
I also tried SDKConfigProvider  and only use MetaMaskProvider and issue still exists.

The solution that works for me is to upgrade into amplify v6.

Thank you for your response.
Regards.
