### ISSUE TITLE
[Bug]: Unity Webgl build failed

### ISSUE THREAD

**Issue by Dejavu0709** [MetaMask/metamask-sdk#715]
### SDK

Unity

### Provide environment information

2021.3.27  Unity Webgl build failed on windows，here is the error log：

Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
Traceback (most recent call last):
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 3571, in <module>
    sys.exit(main(sys.argv))
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 3564, in main
    ret = run(args)
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 1082, in run
    phase_post_link(options, wasm_target, wasm_target, target)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 2400, in phase_post_link
    phase_emscript(options, in_wasm, wasm_target, memfile)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 2428, in phase_emscript
    emscripten.run(in_wasm, wasm_target, final_js, memfile)
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 830, in run
    emscript(in_wasm, out_wasm, outfile_js, memfile, shared.DEBUG)
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 308, in emscript
    glue, forwarded_data = compile_settings()
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 178, in compile_settings
    cwd=path_from_root('src'), env=env)
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 216, in run_js_tool
    return check_call(command, *args, **kw).stdout
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 202, in check_call
    return run_process(cmd, *args, **kw)
  File "C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 97, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 474, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 926, in communicate
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 1049063: illegal multibyte sequence
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()

### MetaMask SDK Version

1.3.0

### MetaMask Mobile app Version

1.3.0

### Describe the Bug

2021.3.27  Unity Webgl build failed on windows

### Expected Behavior

build success

### To Reproduce

instal the Metamask sdk，and build the webgl for the main sample scene

**Comment by ecp4224** [comment]
Did you set the MetaMask WebGL template when building? 
Can you try updating to 1.3.1? 
Are you using anything else other than MetaMask SDK?

**Comment by Dejavu0709** [comment]
> Did you set the MetaMask WebGL template when building? Can you try updating to 1.3.1? Are you using anything else other than MetaMask SDK?

1.I use the Webgl template
2.I will try,
3.No,it is empty project

The same project work on the macos,  I think maybe the UnityEciesProvider.cs cause the issue:

#if (UNITY_IOS || UNITY_TVOS || UNITY_WEBGL) && !UNITY_EDITOR
        private const string libraryName = "__Internal";
#if UNITY_WEBGL && !UNITY_EDITOR
        /// <summary>Initializes the ECIES library.</summary>
        [DllImport(libraryName)]
        private static extern void EciesInitialize();

Webgl build  success on windows without these codes

**Comment by ecp4224** [comment]
Thanks for following up on this, what you did makes sense since WebGL target no longer uses the native ECIES code and instead uses the MetaMask JS SDK directly (which handles ECIES itself).

As a workaround, it should be safe to remove that code, however we will have a proper fix for this in the next release.

**Comment by KuhnDreemurr** [comment]
I had foud what happend with Bee issue :D
That's because if you use any package or API script incloude [DllImport("__Internal")]，you need to have same name .jslib file you called, the file icon in Unity just like a piece of puzzle
![image](https://github.com/MetaMask/metamask-sdk/assets/79293577/8a036f3f-a520-4b57-a2a0-2fcffefcd416)
![image](https://github.com/MetaMask/metamask-sdk/assets/79293577/b26a9939-1d6a-4bbc-95fe-5534d212d4c7)
![image](https://github.com/MetaMask/metamask-sdk/assets/79293577/1d896d47-7961-4b3b-ba9e-aebbe6c8e6b4)

**Comment by christopherferreira9** [comment]
Hi all! We're closing this issue as we now get closer to the release of the Unity SDK version 2.0 which contains this fix. Thank you for reporting!
